### ISSUE TITLE
Error when adding the github action

### ISSUE THREAD

**Issue by kostyantyn** [fionn/newline-linter#1]
Hi,

Thanks for working on such a nice linter! 

While testing it, I see errors:
```
Run fionn/newline-linter@master
Run /home/ubuntu/_work/_actions/fionn/newline-linter/master/git-no-newlines
/__w/_temp/15db5329-070c-4c56-87fe-72c0a6f8d2b4.sh: line 1: /home/ubuntu/_work/_actions/fionn/newline-linter/master/git-no-newlines: No such file or directory
Error: Process completed with exit code 127.
```

Config is the following:
```
    - name: Check newlines
      uses: fionn/newline-linter@master
      with:
        exclusion_pattern: vendor
```

Any hints as to why it doesn't work out of the box?

**Comment by fionn** [comment]
Hi, I am glad you like the linter (even though the action is broken for you).

Are you running in a container on a self-hosted runner? If so, then I think I know what the problem is and will create a branch for you to test.

If not, can you share a complete minimal workflow file so I can try to reproduce it?

**Comment by kostyantyn** [comment]
Hi @fionn . Indeed, I run self-hosted runner.

**Comment by fionn** [comment]
Could you point it at `self-hosted-container` or 875215670b836c57bce69d362ba60be892c041aa and try again?

**Comment by kostyantyn** [comment]
Amazing! works like a charm!

```
cmd/tracer/internal/handlers/decoder/index.html: no newline at end of file
Error: No newline at end of file.
Error: Process completed with exit code 31.
```

This Github action is such a PR-review productivity booster!

**Comment by fionn** [comment]
Great! And I'm very happy it's getting some use outside of my work repos. :)
